# RCAMNet - Detectron2 Config

MODEL:
  META_ARCHITECTURE: "MaskRCNN"
  WEIGHTS: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
  MASK_ON: True
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 5  # number of BLB severity stages
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50

DATASETS:
  TRAIN: ("blb_train",)
  TEST: ("blb_val",)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00025
  MAX_ITER: 10000
  STEPS: (7000, 9000)
  CHECKPOINT_PERIOD: 1000

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

OUTPUT_DIR: "./output"
